# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: schedule CI

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
      - name: run code
        run: node index.js ${{ secrets.URL_DISCORD }}
      - name: Commit and push if changed
        run: |
          git add .
          git diff
          git config --global user.email "bengsiswantoh@gmail.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated Data" -a || echo "No changes to commit"
          git push
